name: Debug APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore signing key
        run: echo "${{ secrets.THE_MI }}" | base64 -d > app/debug.keystore

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"

      - name: Build debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: micast-debug-apk
          path: app/build/outputs/apk/debug/*.apk
